//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_GetAllImage
    {
        public long PostID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string Excerpt { get; set; }
        public string Status { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public long Parent { get; set; }
        public string GUID { get; set; }
        public Nullable<int> Order { get; set; }
        public string Type { get; set; }
        public string CommentStatus { get; set; }
        public int CommentCount { get; set; }
    }
}
